- name: SSH Clients
  hosts: client
  tags:
    - client
  tasks:
    - name: Set SSH key directory
      set_fact:
        ssh_key_dir: "~/.ssh/keys"

    - name: Create SSH key directory
      file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: "u=rwx,g=,o="

    - name: Generate SSH private keys
      shell: "ssh-keygen -b 2048 -t rsa -f {{ ssh_key_dir }}/{{ item }}.key -q -N ''"
      args:
        creates: "{{ ssh_key_dir }}/{{ item }}.key"
      loop: "{{ groups['server'] }}"
      when: item != inventory_hostname

    - name: Save generated public keys
      fetch:
        src: "{{ ssh_key_dir }}/{{ item }}.key.pub"
        dest: "keys/{{ inventory_hostname }}/"
        flat: yes
      loop: "{{ groups['server'] }}"
      when: item != inventory_hostname

- name: SSH Servers
  hosts: server
  tags:
    - server
  strategy: free
  tasks:
    - name: Add SSH keys for SSH clients
      authorized_key:
        state: present
        user: "{{ ansible_env.USER }}"
        key: "{{ item }}"
      with_lines:
        - 'cat keys/*/{{ inventory_hostname }}.key.pub 2>/dev/null | cat'
        - 'cat keys/*/all.key.pub 2>/dev/null | cat'
    - name: Revoke access of old SSH keys
      authorized_key:
        state: absent
        user: "{{ ansible_env.USER }}"
        key: "{{ item }}"
      with_lines:
        - 'cat revoked-keys/*/{{ inventory_hostname }}.key.pub 2>/dev/null | cat'
        - 'cat revoked-keys/*/all.key.pub 2>/dev/null | cat'
